### ISSUE TITLE
Add UI column to specify base-event/inherited attribute vs. net-new attribute

### ISSUE THREAD

**Issue by sfriedfertig** [ocsf/ocsf-server#32]
As discussed in the July 18th, 2023 OCSF zoom: This data is already specified when hovering over an attribute in the UI, but I think it warrants its own column for more convenient reading. This would be particularly helpful for consumers who are actively developing with OCSF (i.e. new developers or those who are more comfortable with visual representations). Again, the data is already there -- just need to reformat it/present it in a more stable way. 

Because this info may not be necessary for passive readers of the schema, it may be worth having this field as a toggle on-and-off.

**Comment by rmouritzen-splunk** [comment]
Closing because this seems to be more or less addressed with recent changes. @sfriedfertig if you want to re-open, please let me know what page(s) would be affected by this? I think this could apply to the Attribute Dictionary page, the class detail pages, and the object detail pages.

In PR #63 the tooltip text on the class detail page was changed to show the hierarchical path to where the attribute is defined up to the current item. PR #77 adds this to the object detail page as well.

At the time of this writing you can see this change on the public https://schema.ocsf.io for class detail pages. For example, click on https://schema.ocsf.io/1.1.0/classes/authentication then hover of the `api` in the "Name" column. If this cover things, we are done. If not, let me know!
